### ISSUE TITLE
Pending Tasks

### ISSUE THREAD

**Issue by linhSUTD** [linhSUTD/interactive-front-end#1]
- [x] Redesign UI Flow: Courses => Course => Lessons => Exercises
- [ ] Profile Page: Name, Reset password, Keep track progress.
- [x] Query Content / Hint 
- [x] Editor Directive
- [x] Console Directive
- [x] Display Course
- [x] Display Lesson
- [x] Display Exercise
- [ ] Query overview course
- [ ] Query overview lesson
- [ ] Plug editor directives into exercise 
- [ ] User: Display user info, update user, reset password, user progress
- User-Related Pages:
    - Login Page: 
    - Register: Confirm password, Send confirmation email (link) => click link => finish.
    - Reset password: gui email => fill new password => finish.
- Course:
    - Get course overview (require authentication)
- Lesson:
    - Get lesson overview (require authentication)

**Comment by tiepvupsu** [comment]
[]lkasjklf

**Comment by tiepvupsu** [comment]
In Creating new exercise:
- [x] Move 'Try exercise' buton to the bottom next to 'Save'. Currently, I have to go down to Save and go up to 'Try exercise'. 
- [x] When click 'Try exercise', code should be saved first. It's redundant if we have to click both butons. 
- [ ] Moveable vertical bar in 'User mode' (Try exercise). This is minor.

**Comment by dhhoang** [comment]
track with other issues
