### ISSUE TITLE
Page Course

### ISSUE THREAD

**Issue by linhSUTD** [linhSUTD/interactive-front-end#11]
- [x] Load thông tin cơ bản
- [x] Sau khi đăng ký course, bị lỗi ko load đc bài giảng.
- [x] Click xem bai giang chi tiet
- [x] Hide xem bai giang chi tiet
- [x] Click vao exercise => vao exercise
- [x] Load %
- [x] Check if exercise đã hoàn thành hay chưa
- [x] Them view Chapter detail

**Comment by dhhoang** [comment]
Chưa hiểu vụ "Them view Chapter detail" lắm @linhSUTD
