### ISSUE TITLE
Lỗi trang chủ

### ISSUE THREAD

**Issue by tiepvupsu** [linhSUTD/interactive-front-end#22]
Lúc anh vào trang chủ thì nó lại hiện cái thông báo "Notice"

Và bên dưới có hai tab "Khoá học đang tham gia" và "Khoá học đã hoàn thành". Tuy nhiên, cái "khoá đang tham gia" trống trơn, cái "Khoá đã hoàn thành" lại hiện khoá đang tham gia. Các chú check lại nhé.

**Comment by dhhoang** [comment]
Cái này là do khi anh nộp bài tập nó sẽ tự động tính điểm, nếu điểm full nó sẽ tự đánh dấu khóa học là đã hoàn thành. Có cách nào hay hơn k nhỉ ?

**Comment by tiepvupsu** [comment]
Cái logic: điểm full tự đánh dấu hoàn thành hoặc nhảy sang bài khác anh nghĩ là một bug lớn. Việc này có thể giải quyết bằng cách đơn giản khác là khi nào tất cả các bài được hoàn thành thì khoá đó mới hoàn thành, hay tất cả các ex được hoàn thành thì lesson mới hoàn thành. 

Với những bài 0 điểm thì nó được coi là hoàn thành nếu người dùng đã click vào link đó.

**Comment by tiepvupsu** [comment]
Hoặc có một cách nữa là với những bài anh chưa cho điểm thì em mặc định là 10 điểm, thay vì 0 như hiện tại. 


EM xem cách này hay cách trên đơn giản hơn. 
Tuy nhiên, có thể vẫn có bug ở những bài mà anh không yêu cầu viết code mà chỉ đọc thôi. Khi đó sẽ không có phần so sánh kết quả mà chỉ có một cái gì để xác định là người dùng đã đọc bài. Đã click vào link chẳng hạn.
