### ISSUE TITLE
Lỗi trong cửa sổ làm bài

### ISSUE THREAD

**Issue by tiepvupsu** [linhSUTD/interactive-front-end#25]
- [x] Lỗi font tiếng Việt ở mấy cái heading. Lỗi nhỏ, nhưng nên sửa. Font và màu sắc khi anh thêm bài và preview khá đẹp, đẹp hơn trên giao diện người dùng nhiều (trừ cái inline code nên để màu đỏ như trên giao diện người dùng). Anh nghĩ cái này Huy sửa được. 

- [x] Khi scroll down phần hướng dẫn (nửa cửa sổ bên trái), thì phần editor (nửa bên phải) cũng bị kéo theo. 

- [x] Khi 'reload' thì nó lại nhảy về chỗ khác mà không giữ nguyên ở trang đang làm bài.

**Comment by dhhoang** [comment]
Cái vụ scroll thì hơi khó anh ạ vì mặc định trình duyệt khi scroll hết cửa sổ con nó sẽ scroll đến cửa số ngoải @tiepvupsu
