### ISSUE TITLE
check output bug

### ISSUE THREAD

**Issue by tiepvupsu** [linhSUTD/interactive-front-end#40]
Khi anh chưa điền 'Correct output' thì output nào cũng đúng.

**Comment by dhhoang** [comment]
Dạ cái này là do khi một bài tập mà không có output thì coi như bài đó không có bài tập anh 😄

**Comment by tiepvupsu** [comment]
Cũng ok. Nhưng có cách nào hiện thị khác đi là 'Kết quả chính xác' không? Tức là không có output thì không hiện chính xác hay không nữa.
