### ISSUE TITLE
'Xảy ra vấn đề trong quá trình xử lý, xin thử lại'

### ISSUE THREAD

**Issue by tiepvupsu** [linhSUTD/interactive-front-end#41]
Nếu lỗi này là do thời gian chạy quá lâu thì em thay bằng 'Code chưa hiệu quả, thời gian chạy quá lâu'

Thêm một điểm nữa là sau khi gặp thông báo này, anh không 'Nộp bài' lại được nữa mà phải refresh mới code và 'Nộp bài' được.

**Comment by dhhoang** [comment]
Fixed with ba99fdb4cc5b8780ef91d12a5943a43700738546
