### ISSUE TITLE
index dạng timestamp hoặc số thực

### ISSUE THREAD

**Issue by tiepvupsu** [linhSUTD/interactive-front-end#42]
Hiện anh xoá hay thêm bớt bài mà điền index thì hơi oải vì phải thay hết index các bài ở sau. 

Nếu chập nhận timestamp hoặc chỗ index đó cho anh điền số thực thì ngon hơn, các chú tự sắp xếp và lấy chỉ số thật sau.

**Comment by dhhoang** [comment]
anh check lại cái này nhé

**Comment by dhhoang** [comment]
@tiepvupsu  anh check lại cái nhé 📦
