### ISSUE TITLE
Nội dung dashboard

### ISSUE THREAD

**Issue by tiepvupsu** [linhSUTD/interactive-front-end#45]
Theo anh, trên trang dashboard, Huy cho cái nội dung bao nhiêu bài đã làm, còn bao nhiêu bài, giống cái ảnh hôm qua em cho anh xem. 

Thêm dòng chữ cố định: 

"Chào mừng bạn đã quay trở lại với Machine Learning cơ bản và FundaML. Chúc bạn một ngày tốt lành."

**Comment by linhSUTD** [comment]
Closed

**Comment by linhSUTD** [comment]
Closed
