### ISSUE TITLE
Góp ý ô giới thiệu course

### ISSUE THREAD

**Issue by dangsonbk** [linhSUTD/interactive-front-end#47]
[fundaml.com/#/courses](http://fundaml.com/#/courses):
Góp ý của em trong ô giới thiệu course ^^:
- Description để line-spacing hơi bé nên nhìn chữ hơi đặc.
- Chữ Beginner nên thiết kế giống tag hoặc đặt vị trí khác, để giống button thì người dùng dễ bấm nhầm vì nghĩ đó là để Read more.

**Comment by linhSUTD** [comment]
Closed
