### ISSUE TITLE
Lỗi hiểu thị thông tin khi login

### ISSUE THREAD

**Issue by dangsonbk** [linhSUTD/interactive-front-end#48]
Hôm nay em vào thử thì bị lỗi này ạ:

Sau khi tạo tài khoản, kích hoạt và login thì được redirect về:  
http://fundaml.com/#/dashboard.

Tuy nhiên khi ở trang này thì:  
- Không chuyển sang homepage được. -> Không chọn được khóa học.

Sau khi thoát ra rồi đăng nhập lại thì có thể vào trang course:  
http://fundaml.com/#/course/5990a766cdc6e32b3b4d0666/intro  
Tuy nhiên khi rời khỏi trang này thì lại bị lỗi như trên, không có đường link back về trang này. Và:  

- Không có thông tin gì ở các tab: Khóa học đang tham gia | Khóa học đã hoàn thành.

**Comment by linhSUTD** [comment]
Fixed

**Comment by linhSUTD** [comment]
Closed
